// Generated by https://quicktype.io

// ignore_for_file: file_names

class TopArtistsModel {
  String? name;
  String? mbid;
  String? url;

  TopArtistsModel({
    this.name,
    this.mbid,
    this.url,
  });

  //Map -> Object
  factory TopArtistsModel.fromMap(Map<String,dynamic> map){
    return TopArtistsModel(
      name: map['name'],
      mbid: map['mbid'],
      url: map['ursl']
    );
  }

  //Object -> Map
  Map<String,dynamic> toMap(){
    return {
      'name': name,
      'mbid': mbid,
      'url': url
    };
  }

}

class Image {
  String? text;
  String? size;

  Image({
    this.text,
    this.size,
  });
}
